package restaurantproject;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Restaurant extends javax.swing.JFrame {
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
        load_table();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tableseat = new javax.swing.JPanel();
        table_seat = new javax.swing.JLabel();
        tableSeat = new javax.swing.JComboBox<>();
        option1 = new javax.swing.JPanel();
        confirm_button = new javax.swing.JButton();
        option2 = new javax.swing.JPanel();
        delete_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        tableseat1 = new javax.swing.JPanel();
        first_name1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        isi_namaakhir1 = new javax.swing.JTextField();
        last_name1 = new javax.swing.JLabel();
        isi_namapertama1 = new javax.swing.JTextField();
        tableseat2 = new javax.swing.JPanel();
        name2 = new javax.swing.JLabel();
        dbooking = new com.toedter.calendar.JDateChooser();
        tableseat3 = new javax.swing.JPanel();
        name3 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        tableseat4 = new javax.swing.JPanel();
        table_seat1 = new javax.swing.JLabel();
        status_c = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        title.setText("Restaurant Booking System");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No pengunjung", "Pengunjung_ID", "Nama depan", "Nama belakang", "Table seat", "Tanggal booking", "Status"
            }
        ));
        table.setCellSelectionEnabled(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        tableseat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table_seat.setText("Table seat");

        tableSeat.setEditable(true);
        tableSeat.setMaximumRowCount(5);
        tableSeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 orang", "2 orang", "3 orang", "4 orang", "5 orang" }));

        javax.swing.GroupLayout tableseatLayout = new javax.swing.GroupLayout(tableseat);
        tableseat.setLayout(tableseatLayout);
        tableseatLayout.setHorizontalGroup(
            tableseatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableseatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table_seat)
                    .addComponent(tableSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        tableseatLayout.setVerticalGroup(
            tableseatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table_seat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        option1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        confirm_button.setText("Konfirmasi booking");
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout option1Layout = new javax.swing.GroupLayout(option1);
        option1.setLayout(option1Layout);
        option1Layout.setHorizontalGroup(
            option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirm_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        option1Layout.setVerticalGroup(
            option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(confirm_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        option2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        delete_button.setText("Hapus");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        reset_button.setText("Reset");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });

        exit_button.setText("Keluar");
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout option2Layout = new javax.swing.GroupLayout(option2);
        option2.setLayout(option2Layout);
        option2Layout.setHorizontalGroup(
            option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option2Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        option2Layout.setVerticalGroup(
            option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(option2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(exit_button)
                    .addComponent(reset_button)
                    .addComponent(update_button)
                    .addComponent(delete_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableseat1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        first_name1.setText("Nama depan *");

        name1.setText("Nama");

        last_name1.setText("Nama belakang *");

        javax.swing.GroupLayout tableseat1Layout = new javax.swing.GroupLayout(tableseat1);
        tableseat1.setLayout(tableseat1Layout);
        tableseat1Layout.setHorizontalGroup(
            tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat1Layout.createSequentialGroup()
                .addGroup(tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableseat1Layout.createSequentialGroup()
                        .addGroup(tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tableseat1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(name1))
                            .addGroup(tableseat1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(last_name1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tableseat1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(first_name1)
                        .addGap(18, 18, 18)
                        .addGroup(tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isi_namaakhir1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(isi_namapertama1))))
                .addContainerGap())
        );
        tableseat1Layout.setVerticalGroup(
            tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(name1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name1)
                    .addComponent(isi_namapertama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tableseat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(last_name1)
                    .addComponent(isi_namaakhir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tableseat2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        name2.setText("Tanggal booking");

        dbooking.setDateFormatString("yyyy-mm-dd");

        javax.swing.GroupLayout tableseat2Layout = new javax.swing.GroupLayout(tableseat2);
        tableseat2.setLayout(tableseat2Layout);
        tableseat2Layout.setHorizontalGroup(
            tableseat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(name2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tableseat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbooking, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        tableseat2Layout.setVerticalGroup(
            tableseat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dbooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableseat3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        name3.setText("Pengunjung_ID");

        javax.swing.GroupLayout tableseat3Layout = new javax.swing.GroupLayout(tableseat3);
        tableseat3.setLayout(tableseat3Layout);
        tableseat3Layout.setHorizontalGroup(
            tableseat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat3Layout.createSequentialGroup()
                .addGroup(tableseat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableseat3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(name3))
                    .addGroup(tableseat3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableseat3Layout.setVerticalGroup(
            tableseat3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name3)
                .addGap(13, 13, 13)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        tableseat4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        table_seat1.setText("Status");

        status_c.setEditable(true);
        status_c.setMaximumRowCount(3);
        status_c.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending", "Cancelled" }));

        javax.swing.GroupLayout tableseat4Layout = new javax.swing.GroupLayout(tableseat4);
        tableseat4.setLayout(tableseat4Layout);
        tableseat4Layout.setHorizontalGroup(
            tableseat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableseat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table_seat1)
                    .addComponent(status_c, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tableseat4Layout.setVerticalGroup(
            tableseat4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableseat4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table_seat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(option2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableseat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tableseat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tableseat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableseat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tableseat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(option1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tableseat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tableseat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(option1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tableseat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tableseat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tableseat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(option2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        
        int baris = table.getSelectedRow();
            String cell = table.getModel().getValueAt(baris,1).toString();
            String sql ="DELETE FROM booking WHERE pengunjung_ID='"+cell+"'";
        
        try {
            
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            load_table();
            kosong();
            
            JOptionPane.showMessageDialog(this, "Berhasil di hapus","Restaurant Booking System",JOptionPane.OK_OPTION);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Restaurant Booking System",JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_delete_buttonActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
      
        try {
            String sql ="UPDATE booking SET pengunjung_ID = '"
                    +ID.getText()+"',namaawal='"+isi_namapertama1.getText()+"',namaakhir= '"+isi_namaakhir1.getText()
                    +"',tableS= '"+tableSeat.getSelectedItem()+"',dbooking='"+
                    ((JTextField)dbooking.getDateEditor().getUiComponent()).getText()+
                    "',status='"+status_c.getSelectedItem()+"' WHERE pengunjung_ID='"+ID.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "data berhasil di edit","Restaurant Booking System",JOptionPane.OK_OPTION);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan data gagal"+e.getMessage(),"Restaurant Booking System",JOptionPane.OK_OPTION);
        }
        load_table();
        kosong(); //blm berhasil ntar dilanjutin
        
    }//GEN-LAST:event_update_buttonActionPerformed

    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
        kosong();
    }//GEN-LAST:event_reset_buttonActionPerformed
    
    private JFrame frame;
    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Konfirmasi kalau Anda keluar ", "Restaurant Booking System",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed

        try{
            String sql = "INSERT INTO booking (pengunjung_ID, namaawal, namaakhir, tableS, dbooking, status) "
                    + "VALUES ('"+ID.getText()+"','"+isi_namapertama1.getText()+
                    "','"+isi_namaakhir1.getText()+"','"+
                    tableSeat.getSelectedItem()+"','"+((JTextField)dbooking.getDateEditor().getUiComponent()).getText()+
                    "','"+status_c.getSelectedItem()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showConfirmDialog(null, "Booking telah dikonfirmasi! ","Restaurant Booking System",JOptionPane.OK_OPTION);
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        load_table();
        kosong();
        
    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int baris = table.rowAtPoint(evt.getPoint());
        
        String no = table.getValueAt(baris, 1).toString();
        String nA = table.getValueAt(baris, 2).toString();
        String nAk = table.getValueAt(baris, 3).toString();        
        String pesanantable = table.getValueAt(baris, 4).toString();
        String stat = table.getValueAt(baris,6).toString();

        ID.setText(no);
        isi_namapertama1.setText(nA);
        isi_namaakhir1.setText(nAk);
        tableSeat.setSelectedItem(pesanantable);
        status_c.setSelectedItem(stat);
        
        //set date untuk baris 5
        try {
           Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)table.getValueAt(baris, 5));
           dbooking.setDate(date); 
        } catch (ParseException ex) {
          Logger.getLogger(Restaurant.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_tableMouseClicked

    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Pengunjung ID");
        model.addColumn("Nama depan");
        model.addColumn("Nama belakang");
        model.addColumn("Table seat");
        model.addColumn("Tanggal booking");
        model.addColumn("Status");
        
        try{
            int no =1;
            String sql = "select * from booking";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3)
                        ,res.getString(4), res.getString(5), res.getString(6)
                });//no, pengunjung ID, nama depan, nama belakang, table seat, tgl booking, status pelanggan 
                
                table.setModel(model);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tableSeat.addItem("1 orang");
        tableSeat.addItem("2 orang");
        tableSeat.addItem("3 orang");
        tableSeat.addItem("4 orang");
        tableSeat.addItem("5 orang");
        
        status_c.addItem("Active");
        status_c.addItem("Pending");
        status_c.addItem("Cancelled");
    }
    
    private void kosong() {
        ID.setText(null);
        isi_namapertama1.setText(null);
        isi_namaakhir1.setText(null);
        tableSeat.setSelectedItem("Pilih");
        dbooking.setDate(null);
        status_c.setSelectedItem("Active");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton confirm_button;
    private com.toedter.calendar.JDateChooser dbooking;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel first_name1;
    private javax.swing.JTextField isi_namaakhir1;
    private javax.swing.JTextField isi_namapertama1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel last_name1;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JPanel option1;
    private javax.swing.JPanel option2;
    private javax.swing.JButton reset_button;
    private javax.swing.JComboBox<String> status_c;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> tableSeat;
    private javax.swing.JLabel table_seat;
    private javax.swing.JLabel table_seat1;
    private javax.swing.JPanel tableseat;
    private javax.swing.JPanel tableseat1;
    private javax.swing.JPanel tableseat2;
    private javax.swing.JPanel tableseat3;
    private javax.swing.JPanel tableseat4;
    private javax.swing.JLabel title;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}